# Generated by Django 5.0.1 on 2024-01-27 13:17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=320, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("role", models.PositiveSmallIntegerField(choices=[(1, "User"), (2, "Anonymous")], default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
